<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>toml</string>
		<string>tml</string>
	</array>
	<key>name</key>
	<string>TOML</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.section.begin.toml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.section.toml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.section.end.toml</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Key group</string>
			<key>match</key>
			<string>^\s*(\[)(.*?)(\])\s*</string>
			<key>name</key>
			<string>meta.tag.section.toml</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#dataTypes</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.toml</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Comments - whole line or partial</string>
					<key>match</key>
					<string>((#).*$)</string>
					<key>name</key>
					<string>comment.line.number-sign.toml</string>
				</dict>
			</array>
		</dict>
		<key>dataTypes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.toml</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>String</string>
					<key>end</key>
					<string>(?&lt;!\\)"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.toml</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.name.value.toml</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Datetime - ISO8601 dates</string>
					<key>match</key>
					<string>(\d{4})-(0[1-9]|1[0-2])-(0[1-9]|1[0-9]|2[0-9]|3[0-1])T(0[0-9]|1[0-9]|2[0-3]):(0[0-9]|1[0-9]|2[0-9]|3[0-9]|4[0-9]|5[0-9]):(0[0-9]|1[0-9]|2[0-9]|3[0-9]|4[0-9]|5[0-9])Z</string>
					<key>name</key>
					<string>constant.other.date.toml</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Float</string>
					<key>match</key>
					<string>(-?[0-9]+)\.([0-9]+)</string>
					<key>name</key>
					<string>constant.numeric.float.toml</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Integer</string>
					<key>match</key>
					<string>-?[0-9]+</string>
					<key>name</key>
					<string>constant.numeric.integer.toml</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Boolean</string>
					<key>match</key>
					<string>(true|false)</string>
					<key>name</key>
					<string>constant.language,boolean.toml</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\[</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.array.begin.toml</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Array</string>
					<key>end</key>
					<string>\]</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.array.end.toml</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.array.toml</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#dataTypes</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.toml</string>
	<key>uuid</key>
	<string>9b00c027-8f13-4f5a-a57e-d90478a1f817</string>
</dict>
</plist>
